export const BRAND_NAME = 'Policy Dog'
export const BRAND_TAGLINE = 'Regulatory Compliance Platform'
export const BROWSER_TITLE = `${BRAND_NAME} - ${BRAND_TAGLINE}`
export const BRAND_MONOGRAM = 'P'
export const HELP_GUIDE_DESCRIPTION = `Learn how to use ${BRAND_NAME}`
export const HELP_GUIDE_SUMMARY = `Use ${BRAND_NAME} to monitor regulatory changes and assess their impact on your business.`
export const SHARE_CARD_FOOTER = `Generated by ${BRAND_NAME}`
export const SHARE_CARD_QR_HINT = `Scan the QR code to open the full report in ${BRAND_NAME}`
export const SHARE_IMAGE_PREFIX = 'policy-dog'

export const buildShareImageFilename = (market: string, slug: string) =>
  `${SHARE_IMAGE_PREFIX}-${market}-${slug}.png`
